# Generated by Django 3.1 on 2020-08-31 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=10000)),
                ('totalSubmission', models.IntegerField(default=0)),
                ('SuccessfulSubmission', models.IntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerequired', models.IntegerField()),
                ('spacerequired', models.IntegerField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.questions')),
            ],
        ),
        migrations.AlterField(
            model_name='submissions',
            name='quesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.questions'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
