# Generated by Django 3.1 on 2020-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='def_lang',
            field=models.CharField(default='cpp', max_length=5),
        ),
        migrations.AddField(
            model_name='questions',
            name='testcases',
            field=models.IntegerField(default=0),
        ),
    ]
