# Generated by Django 3.1.1 on 2020-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200917_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quesDesc',
            field=models.TextField(default='Sample Question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quesTitle',
            field=models.CharField(default='Warmup', max_length=255),
        ),
    ]
