# Generated by Django 3.1.1 on 2020-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200918_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quesDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quesTitle',
            field=models.CharField(max_length=255),
        ),
    ]
