# Generated by Django 3.1.1 on 2020-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200918_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='totalSubmision',
            field=models.IntegerField(default=1),
        ),
    ]
