# Generated by Django 3.1.1 on 2020-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_questions_totalsubmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='SuccessfulSubmission',
            field=models.IntegerField(default=0),
        ),
    ]
