# Generated by Django 3.1.1 on 2020-09-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_questions_successfulsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
