# Generated by Django 3.1.1 on 2020-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_questions_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
