# Generated by Django 3.1 on 2020-10-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0008_submissions_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='multipleQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreQuestion', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('attempt', models.IntegerField(default=0)),
                ('out', models.IntegerField(default=0)),
                ('subStatus', models.CharField(default='NA', max_length=5)),
                ('subTime', models.CharField(default='', max_length=50)),
                ('subScore', models.IntegerField(default=0)),
                ('correctTestCases', models.IntegerField(default=0)),
                ('TestCasesPercentage', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
