# Generated by Django 3.1 on 2020-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20201008_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='que',
            new_name='quesID',
        ),
    ]
