# Generated by Django 3.1.3 on 2021-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20201029_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(default='junior', max_length=6),
        ),
        migrations.AddField(
            model_name='questions',
            name='category_tag',
            field=models.CharField(default='junior', max_length=6),
        ),
    ]
