# Generated by Django 3.1.4 on 2021-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userprofile_correctly_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
    ]
