# Generated by Django 3.1.4 on 2021-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_userprofile_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='iformat',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='oformat',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='quesDesc',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='sampleInput',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='question',
            name='sampleOutput',
            field=models.TextField(default='NA'),
        ),
    ]
