# Generated by Django 3.1.4 on 2021-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20210131_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quesDesc',
        ),
    ]
