# Generated by Django 3.1.4 on 2021-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_remove_question_quesdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='qid',
            field=models.IntegerField(default=1),
        ),
    ]
