# Generated by Django 3.1.4 on 2021-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_submission_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cheatcounter',
            field=models.IntegerField(default=3),
        ),
    ]
