# Generated by Django 3.1.4 on 2021-02-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_userprofile_cheatcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone2',
        ),
    ]
